# Generated by Django 5.1 on 2024-10-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
            preserve_default=False,
        ),
    ]
