# Generated by Django 5.1 on 2024-10-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_boardstatus'),
        ('tasks', '0004_alter_task_description_alter_taskstatus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.boardstatus'),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
